language: php

php:
- 7.2

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install lftp fontforge
- composer self-update
- composer install
- nvm install 9
- npm install --global grunt-cli
- npm install
- cd vendor/redaxscript/redaxscript && npm install && cd -

script:
- grunt build --gruntfile vendor/redaxscript/redaxscript/gruntfile.js
- grunt
- grunt config
- grunt install

after_success:
- grunt deploy

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
