language: php

php: 7.2

addons:
 apt:
  packages:
  - lftp
  - fontforge

before_install:
- composer global require hirak/prestissimo

install:
- composer install
- nvm install 10
- npm install --global grunt-cli
- npm install
- cd vendor/redaxscript/redaxscript && npm install && cd -

script:
- grunt build --gruntfile vendor/redaxscript/redaxscript/gruntfile.js
- grunt
- grunt config
- grunt install
- grunt lock

after_success:
- grunt deploy

notifications:
 email:
 - team@redaxscript.com
